"""
100 Jazz Standards — Chord Progressions Database
Each entry: title, composer, key, tempo (BPM), style, bars, chord_progression
Progressions use standard jazz chord notation.
"""

JAZZ_STANDARDS = [
    {
        "id": 1,
        "title": "Autumn Leaves",
        "composer": "Joseph Kosma",
        "key": "Gm",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cm7", "F7", "Bbmaj7", "Ebmaj7",
            "Am7b5", "D7", "Gm", "Gm",
            "Cm7", "F7", "Bbmaj7", "Ebmaj7",
            "Am7b5", "D7", "Gm", "Gm",
            "Am7b5", "D7", "Gm", "Gm7",
            "Cm7", "F7", "Bbmaj7", "Ebmaj7",
            "Am7b5", "D7alt", "Gm", "Gm",
            "Am7b5", "D7", "Gm", "Gm",
        ],
    },
    {
        "id": 2,
        "title": "All The Things You Are",
        "composer": "Jerome Kern",
        "key": "F",
        "tempo": 160,
        "style": "jazz",
        "form": "ABAC",
        "bars": 36,
        "progression": [
            "Fm7", "Bbm7", "Eb7", "Abmaj7",
            "Dbmaj7", "Gm7", "C7", "Cmaj7",
            "Cmaj7", "Cm7", "F7", "Bbmaj7",
            "Ebmaj7", "Am7", "D7", "Gmaj7",
            "Gmaj7", "Am7", "Bm7", "Bm7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Cm7", "F7", "Bbmaj7", "Ebmaj7",
            "Abmaj7", "Dm7b5", "G7", "Cm7",
        ],
    },
    {
        "id": 3,
        "title": "Blue Bossa",
        "composer": "Kenny Dorham",
        "key": "Cm",
        "tempo": 160,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Ebm7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 4,
        "title": "Fly Me To The Moon",
        "composer": "Bart Howard",
        "key": "C",
        "tempo": 120,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Am7", "Dm7", "G7", "Cmaj7",
            "Fmaj7", "Bm7b5", "E7", "Am7",
            "Am7", "Dm7", "G7", "Cmaj7",
            "Fmaj7", "Bm7b5", "E7", "Am7",
            "Am7", "Dm7", "G7", "Cmaj7",
            "Fmaj7", "Bm7b5", "E7", "Am7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 5,
        "title": "Summertime",
        "composer": "George Gershwin",
        "key": "Am",
        "tempo": 90,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Am", "Am", "E7", "E7",
            "Am", "Am", "E7", "E7",
            "Am", "Dm", "Am", "Am",
            "E7", "Dm", "Am", "Am",
        ],
    },
    {
        "id": 6,
        "title": "Take The A Train",
        "composer": "Billy Strayhorn",
        "key": "C",
        "tempo": 180,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "C6", "C6", "D7", "D7",
            "Dm7", "G7", "C6", "C6",
            "C6", "C6", "D7", "D7",
            "Dm7", "G7", "C6", "C6",
            "Am7", "D7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "C6", "C6", "D7", "D7",
            "Dm7", "G7", "C6", "C6",
        ],
    },
    {
        "id": 7,
        "title": "My Favorite Things",
        "composer": "Richard Rodgers",
        "key": "Em",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Em7", "Em7", "Em7", "Em7",
            "Em7", "Em7", "Em7", "Em7",
            "Emaj7", "Emaj7", "Emaj7", "Emaj7",
            "Em7", "Em7", "Em7", "Em7",
        ],
    },
    {
        "id": 8,
        "title": "Cantaloupe Island",
        "composer": "Herbie Hancock",
        "key": "Fm",
        "tempo": 120,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Fm7", "Fm7", "Fm7", "Fm7",
            "Db7", "Db7", "Fm7", "Fm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Fm7", "Fm7", "Fm7", "Fm7",
        ],
    },
    {
        "id": 9,
        "title": "So What",
        "composer": "Miles Davis",
        "key": "Dm",
        "tempo": 136,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Ebm7", "Ebm7", "Ebm7", "Ebm7",
            "Ebm7", "Ebm7", "Ebm7", "Ebm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 10,
        "title": "Impressions",
        "composer": "John Coltrane",
        "key": "Dm",
        "tempo": 240,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Ebm7", "Ebm7", "Ebm7", "Ebm7",
            "Ebm7", "Ebm7", "Ebm7", "Ebm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 11,
        "title": "All Of Me",
        "composer": "Gerald Marks",
        "key": "C",
        "tempo": 120,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "C6", "C6", "C7", "C7",
            "Fmaj7", "Fm6", "C6", "E7",
            "Am7", "Am7", "E7", "E7",
            "Am7", "Am7", "D7", "D7",
            "Dm7", "Em7", "Dm7", "Em7",
            "Dm7", "Em7", "Am7", "D7",
            "C6", "C6", "Dm7", "G7",
            "C6", "C6", "C6", "C6",
        ],
    },
    {
        "id": 12,
        "title": "Misty",
        "composer": "Erroll Garner",
        "key": "Eb",
        "tempo": 80,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Ebmaj7", "Bbm7", "Eb7", "Abmaj7",
            "Db7", "Ebmaj7", "Cm7", "F7",
            "Bbm7", "Eb7", "Abmaj7", "Gm7",
            "Cm7", "F7", "Bbm7", "Eb7",
            "Ebmaj7", "Bbm7", "Eb7", "Abmaj7",
            "Db7", "Ebmaj7", "Cm7", "F7",
            "Bbm7", "Eb7", "Abmaj7", "Fm7",
            "Bb7", "Ebmaj7", "Ebmaj7", "Ebmaj7",
        ],
    },
    {
        "id": 13,
        "title": "Satin Doll",
        "composer": "Duke Ellington",
        "key": "C",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Dm7", "G7", "Dm7", "G7",
            "Em7", "A7", "Em7", "A7",
            "Dm7", "G7", "Em7", "A7",
            "Am7", "D7", "Dm7", "G7",
            "Dm7", "G7", "Dm7", "G7",
            "Em7", "A7", "Em7", "A7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 14,
        "title": "Girl From Ipanema",
        "composer": "Antonio Carlos Jobim",
        "key": "F",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "G7", "G7",
            "Gm7", "F#dim7", "Fmaj7", "D7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "G7", "G7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "G7", "G7",
            "Gm7", "F#dim7", "Fmaj7", "D7",
            "Gm7", "C7", "Am7", "D7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 15,
        "title": "Night And Day",
        "composer": "Cole Porter",
        "key": "C",
        "tempo": 160,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Em7", "Am7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Em7", "Am7", "Dm7", "G7",
            "Fmaj7", "Fm6", "Cmaj7", "Am7",
            "Dm7", "G7", "Em7", "A7",
            "Dm7", "G7", "Cmaj7", "Am7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 16,
        "title": "Stella By Starlight",
        "composer": "Victor Young",
        "key": "Bb",
        "tempo": 140,
        "style": "jazz",
        "form": "ABCA",
        "bars": 32,
        "progression": [
            "Am7b5", "D7", "Gm7", "C7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Am7b5", "D7", "Gm7", "C7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Fm7", "Bb7", "Ebmaj7", "C7",
            "Fm7", "Bb7", "Ebmaj7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
        ],
    },
    {
        "id": 17,
        "title": "There Will Never Be Another You",
        "composer": "Harry Warren",
        "key": "Eb",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Gm7", "C7", "Fm7", "Bb7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Gm7", "C7", "Fm7", "Bb7",
            "Ebmaj7", "Eb7", "Abmaj7", "Abm6",
            "Ebmaj7", "C7", "Fm7", "Bb7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Gm7", "C7", "Fm7", "Bb7",
        ],
    },
    {
        "id": 18,
        "title": "Wave",
        "composer": "Antonio Carlos Jobim",
        "key": "D",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Dmaj7", "Dmaj7", "Dmaj7", "Dmaj7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
            "D7", "D7", "Gmaj7", "Gm6",
            "Dmaj7", "Dmaj7", "Dmaj7", "Dmaj7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
            "Em7", "A7", "F#m7", "B7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
        ],
    },
    {
        "id": 19,
        "title": "How High The Moon",
        "composer": "Morgan Lewis",
        "key": "G",
        "tempo": 160,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Gmaj7", "Gmaj7", "Gmaj7", "Gm7",
            "C7", "C7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbm7",
            "Eb7", "Eb7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gm7",
            "C7", "C7", "Cm7", "F7",
            "Bbmaj7", "Am7", "D7", "D7",
            "Gmaj7", "Am7", "D7", "Gmaj7",
        ],
    },
    {
        "id": 20,
        "title": "Body And Soul",
        "composer": "Johnny Green",
        "key": "Db",
        "tempo": 80,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Dbmaj7", "Ebm7", "Fm7", "Gbm7",
            "B7", "Bbm7", "Eb7", "Ebm7",
            "Ab7", "Dbmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Bbm7", "Eb7", "Abmaj7", "Dbmaj7",
            "Ab7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
        ],
    },
    {
        "id": 21,
        "title": "I Got Rhythm",
        "composer": "George Gershwin",
        "key": "Bb",
        "tempo": 200,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Bbmaj7", "Gm7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Gm7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Am7", "D7",
            "Bbmaj7", "Gm7", "Cm7", "F7",
            "Bbmaj7", "F7", "Bbmaj7", "Bbmaj7",
        ],
    },
    {
        "id": 22,
        "title": "Just Friends",
        "composer": "John Klenner",
        "key": "G",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "Am7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
        ],
    },
    {
        "id": 23,
        "title": "My Funny Valentine",
        "composer": "Richard Rodgers",
        "key": "Cm",
        "tempo": 80,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cm", "Cm", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
            "Cm7", "F7", "Dm7b5", "G7",
            "Cm", "Cm", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
            "Cm7", "F7", "Dm7b5", "G7",
            "Cm", "Ab7", "Cm", "Cm",
            "Dm7b5", "G7", "Cm", "Cm",
        ],
    },
    {
        "id": 24,
        "title": "The Days Of Wine And Roses",
        "composer": "Henry Mancini",
        "key": "F",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Fmaj7", "Am7b5", "D7", "Gm7",
            "C7", "Am7b5", "D7", "Gm7",
            "C7", "Fmaj7", "Am7b5", "D7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Am7b5", "D7", "Gm7", "C7",
            "Fmaj7", "Am7b5", "D7", "Gm7",
            "C7", "Am7b5", "D7", "Gm7",
            "C7", "Fmaj7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 25,
        "title": "Softly As In A Morning Sunrise",
        "composer": "Sigmund Romberg",
        "key": "Cm",
        "tempo": 200,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Cm7", "Cm7",
            "G7", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Cm7", "Cm7",
            "G7", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 26,
        "title": "What Is This Thing Called Love",
        "composer": "Cole Porter",
        "key": "C",
        "tempo": 200,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Cmaj7", "Am7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Cmaj7", "Am7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "Am7", "Dm7", "G7",
            "Cmaj7", "Am7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 27,
        "title": "There Is No Greater Love",
        "composer": "Isham Jones",
        "key": "Bb",
        "tempo": 120,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Bbmaj7", "Cm7", "Dm7", "Eb7",
            "F7", "Cm7", "F7", "Bbmaj7",
            "Bbmaj7", "Cm7", "Dm7", "Eb7",
            "F7", "Cm7", "F7", "Bbmaj7",
            "Dm7", "G7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Cm7", "Dm7", "Eb7",
            "F7", "Cm7", "F7", "Bbmaj7",
        ],
    },
    {
        "id": 28,
        "title": "Alone Together",
        "composer": "Arthur Schwartz",
        "key": "Dm",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Gm7", "C7", "Fmaj7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Am7", "D7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Gm7", "C7", "Fmaj7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Am7", "D7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 29,
        "title": "Caravan",
        "composer": "Juan Tizol",
        "key": "Cm",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Cm", "Cm", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
            "Ab7", "Ab7", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
            "Ab7", "Ab7", "Cm", "Cm",
            "Cm", "Cm", "Cm", "Cm",
        ],
    },
    {
        "id": 30,
        "title": "Cherokee",
        "composer": "Ray Noble",
        "key": "Bb",
        "tempo": 260,
        "style": "jazz",
        "form": "AABA",
        "bars": 64,
        "progression": [
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Ebm7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Ebm7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Gm7", "C7", "Bbmaj7", "Bbmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Ebm7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
        ],
    },
    {
        "id": 31,
        "title": "Corcovado",
        "composer": "Antonio Carlos Jobim",
        "key": "F",
        "tempo": 100,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Fmaj7", "Fmaj7", "G7", "G7",
            "G7", "G7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Fmaj7", "Fmaj7", "G7", "G7",
            "G7", "G7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 32,
        "title": "Desafinado",
        "composer": "Antonio Carlos Jobim",
        "key": "G",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "F#7", "F#7", "Bm7", "Bm7",
            "Bm7", "E7", "Am7", "Am7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "F#7", "F#7", "Bm7", "Bm7",
            "Bm7", "E7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
        ],
    },
    {
        "id": 33,
        "title": "Dolphin Dance",
        "composer": "Herbie Hancock",
        "key": "Eb",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Ebmaj7", "Dm7", "Ebmaj7", "Dm7",
            "Cm7", "Fm7", "Bb7", "Ebmaj7",
            "Ebmaj7", "Dm7", "Ebmaj7", "Dm7",
            "Cm7", "Fm7", "Bb7", "Ebmaj7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Ebmaj7", "Dm7", "Cm7", "Fm7",
            "Bb7", "Ebmaj7", "Ebmaj7", "Ebmaj7",
        ],
    },
    {
        "id": 34,
        "title": "Donna Lee",
        "composer": "Charlie Parker",
        "key": "Ab",
        "tempo": 220,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Abmaj7", "F7", "Bbm7", "Eb7",
            "Abmaj7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Bbm7", "Eb7", "Abmaj7", "F7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Abmaj7", "F7", "Bbm7", "Eb7",
            "Abmaj7", "Ab7", "Dbmaj7", "Dbmaj7",
            "Bbm7", "Eb7", "Cm7", "F7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
        ],
    },
    {
        "id": 35,
        "title": "Footprints",
        "composer": "Wayne Shorter",
        "key": "Cm",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 24,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 36,
        "title": "Giant Steps",
        "composer": "John Coltrane",
        "key": "B",
        "tempo": 280,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Bmaj7", "D7", "Gmaj7", "Bb7",
            "Ebmaj7", "Am7", "D7", "Gmaj7",
            "Bb7", "Ebmaj7", "Am7", "D7",
            "Gmaj7", "Bb7", "Ebmaj7", "F#7",
            "Bmaj7", "Fm7", "Bb7", "Ebmaj7",
            "Am7", "D7", "Gmaj7", "Bb7",
            "Ebmaj7", "Am7", "D7", "Gmaj7",
            "Bb7", "Ebmaj7", "Bmaj7", "Bmaj7",
        ],
    },
    {
        "id": 37,
        "title": "Have You Met Miss Jones",
        "composer": "Richard Rodgers",
        "key": "F",
        "tempo": 160,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Em7", "A7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 38,
        "title": "I Remember Clifford",
        "composer": "Benny Golson",
        "key": "Bb",
        "tempo": 100,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "F7", "F7", "Bbmaj7", "Bbmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Dm7b5", "G7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
        ],
    },
    {
        "id": 39,
        "title": "In A Sentimental Mood",
        "composer": "Duke Ellington",
        "key": "Dm",
        "tempo": 72,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Em7b5", "A7",
            "Dm7", "Dm7", "Gm7", "Gm7",
            "C7", "C7", "Fmaj7", "Fmaj7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Em7b5", "A7",
            "Dm7", "Dm7", "Gm7", "Gm7",
            "C7", "C7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 40,
        "title": "Invitation",
        "composer": "Bronislaw Kaper",
        "key": "Cm",
        "tempo": 160,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Cm7", "Cm7", "Fm7", "Fm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 41,
        "title": "It Could Happen To You",
        "composer": "Jimmy Van Heusen",
        "key": "Db",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Dbmaj7", "Dbmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Dbmaj7", "Dbmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Fm7", "Bb7", "Ebm7", "Ab7",
            "Dbmaj7", "Dbmaj7", "Bbm7", "Eb7",
            "Dbmaj7", "Dbmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Dbmaj7", "Dbmaj7",
        ],
    },
    {
        "id": 42,
        "title": "Joy Spring",
        "composer": "Clifford Brown",
        "key": "F",
        "tempo": 220,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Fmaj7", "Gm7", "Am7", "Bbmaj7",
            "Cm7", "Dm7", "Em7", "Fmaj7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Am7", "Gm7", "C7",
            "Fmaj7", "Gm7", "Am7", "Bbmaj7",
            "Cm7", "Dm7", "Em7", "Fmaj7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "C7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 43,
        "title": "Lady Bird",
        "composer": "Tadd Dameron",
        "key": "C",
        "tempo": 160,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cmaj7", "Cmaj7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gbmaj7", "Gbmaj7",
            "Fm7", "Bb7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 44,
        "title": "Like Someone In Love",
        "composer": "Jimmy Van Heusen",
        "key": "C",
        "tempo": 130,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cmaj7", "Dm7", "Em7", "Fmaj7",
            "Em7", "A7", "Dm7", "G7",
            "Cmaj7", "Dm7", "Em7", "Fmaj7",
            "Em7", "A7", "Dm7", "G7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "C7", "Fmaj7", "Fm6",
            "Cmaj7", "A7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 45,
        "title": "Lush Life",
        "composer": "Billy Strayhorn",
        "key": "Db",
        "tempo": 72,
        "style": "jazz",
        "form": "AAB",
        "bars": 36,
        "progression": [
            "Dbmaj7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
            "Dbmaj7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
            "Dbmaj7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
            "Dbmaj7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
            "Dbmaj7", "Bbm7", "Eb7", "Ab7",
            "Dbmaj7", "Bbm7", "Eb7", "Ab7",
            "Dbmaj7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
            "Fm7", "Bbm7", "Eb7", "Abmaj7",
            "Dbmaj7", "Dbmaj7", "Dbmaj7", "Dbmaj7",
        ],
    },
    {
        "id": 46,
        "title": "Maiden Voyage",
        "composer": "Herbie Hancock",
        "key": "D",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "D7sus4", "D7sus4", "D7sus4", "D7sus4",
            "F7sus4", "F7sus4", "F7sus4", "F7sus4",
            "D7sus4", "D7sus4", "D7sus4", "D7sus4",
            "F7sus4", "F7sus4", "F7sus4", "F7sus4",
        ],
    },
    {
        "id": 47,
        "title": "Mercy Mercy Mercy",
        "composer": "Joe Zawinul",
        "key": "Bb",
        "tempo": 110,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Ebmaj7", "Ebmaj7", "Ebmaj7", "Ebmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
        ],
    },
    {
        "id": 48,
        "title": "Mr. PC",
        "composer": "John Coltrane",
        "key": "Cm",
        "tempo": 200,
        "style": "jazz",
        "form": "AB",
        "bars": 12,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "G7", "Fm7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 49,
        "title": "My One And Only Love",
        "composer": "Guy Wood",
        "key": "C",
        "tempo": 72,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
            "Em7", "Am7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Am7", "D7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 50,
        "title": "Nardis",
        "composer": "Miles Davis",
        "key": "Em",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Em7", "Em7", "Em7", "Em7",
            "Em7", "Em7", "Em7", "Em7",
            "Em7", "Em7", "Em7", "Em7",
            "B7", "B7", "Em7", "Em7",
        ],
    },
    {
        "id": 51,
        "title": "Oleo",
        "composer": "Sonny Rollins",
        "key": "Bb",
        "tempo": 220,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Bbmaj7", "G7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "G7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Am7", "D7",
            "Bbmaj7", "G7", "Cm7", "F7",
            "Bbmaj7", "F7", "Bbmaj7", "Bbmaj7",
        ],
    },
    {
        "id": 52,
        "title": "On Green Dolphin Street",
        "composer": "Bronislaw Kaper",
        "key": "Eb",
        "tempo": 160,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Ebmaj7", "Ebmaj7", "Ebm7", "Ab7",
            "Dbmaj7", "Dbmaj7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Ebmaj7", "Ebmaj7", "Ebm7", "Ab7",
            "Dbmaj7", "Dbmaj7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 53,
        "title": "On The Sunny Side Of The Street",
        "composer": "Jimmy McHugh",
        "key": "C",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "C6", "C6", "C6", "C6",
            "Am7", "D7", "Dm7", "G7",
            "C6", "C6", "C6", "C6",
            "Dm7", "G7", "C6", "C6",
            "Am7", "D7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "C6", "C6", "Am7", "D7",
            "Dm7", "G7", "C6", "C6",
        ],
    },
    {
        "id": 54,
        "title": "Ornithology",
        "composer": "Charlie Parker",
        "key": "G",
        "tempo": 220,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Gmaj7", "Gmaj7", "Em7", "A7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Gmaj7", "Gmaj7", "Em7", "A7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Em7", "A7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Em7", "A7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
        ],
    },
    {
        "id": 55,
        "title": "Pent Up House",
        "composer": "Sonny Rollins",
        "key": "G",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "Am7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "Am7",
        ],
    },
    {
        "id": 56,
        "title": "Recorda Me",
        "composer": "Joe Henderson",
        "key": "Dm",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Am7", "D7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 57,
        "title": "Round Midnight",
        "composer": "Thelonious Monk",
        "key": "Eb",
        "tempo": 72,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Ebm7", "Ebm7", "Ebm7", "Ebm7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Am7", "D7", "Gm7", "Gm7",
            "F#m7", "B7", "Emaj7", "Emaj7",
            "Ebm7", "Ebm7", "Ebm7", "Ebm7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Am7", "D7", "Gm7", "Gm7",
            "Bbm7", "Eb7", "Ebm7", "Ebm7",
        ],
    },
    {
        "id": 58,
        "title": "Scrapple From The Apple",
        "composer": "Charlie Parker",
        "key": "F",
        "tempo": 200,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Cm7", "F7",
            "Bbmaj7", "Bbmaj7", "Am7", "D7",
            "Gm7", "C7", "Am7", "D7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 59,
        "title": "Solar",
        "composer": "Miles Davis",
        "key": "Cm",
        "tempo": 140,
        "style": "jazz",
        "form": "ABCA",
        "bars": 24,
        "progression": [
            "Cm7", "Cm7", "Fm7", "Bb7",
            "Ebmaj7", "Ebmaj7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "Cm7", "Cm7", "Fm7", "Bb7",
            "Ebmaj7", "Ebmaj7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 60,
        "title": "Song For My Father",
        "composer": "Horace Silver",
        "key": "Fm",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Fm7", "Fm7", "Fm7", "Fm7",
            "Fm7", "Fm7", "Fm7", "Fm7",
            "Bbm7", "Bbm7", "Bbm7", "Bbm7",
            "Fm7", "Fm7", "Fm7", "Fm7",
        ],
    },
    {
        "id": 61,
        "title": "Speak Low",
        "composer": "Kurt Weill",
        "key": "G",
        "tempo": 140,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Gmaj7", "Gmaj7", "Bm7", "E7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "Am7", "D7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
        ],
    },
    {
        "id": 62,
        "title": "St. Thomas",
        "composer": "Sonny Rollins",
        "key": "C",
        "tempo": 200,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "C6", "C6", "C6", "C6",
            "Dm7", "G7", "C6", "C6",
            "C6", "C6", "C6", "C6",
            "Dm7", "G7", "C6", "C6",
        ],
    },
    {
        "id": 63,
        "title": "Star Eyes",
        "composer": "Gene de Paul",
        "key": "Eb",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Dm7", "G7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
            "Ebmaj7", "Cm7", "Fm7", "Bb7",
        ],
    },
    {
        "id": 64,
        "title": "Stolen Moments",
        "composer": "Oliver Nelson",
        "key": "Cm",
        "tempo": 110,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cm7", "Dm7b5", "G7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Dm7b5",
            "Cm7", "Dm7b5", "G7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
        ],
    },
    {
        "id": 65,
        "title": "Stompin' At The Savoy",
        "composer": "Chick Webb",
        "key": "Ab",
        "tempo": 180,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Abmaj7", "Fm7", "Bbm7", "Eb7",
            "Abmaj7", "Fm7", "Bbm7", "Eb7",
            "Abmaj7", "Fm7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Abmaj7", "Abmaj7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Bbm7", "Eb7", "Abmaj7", "Abmaj7",
            "Abmaj7", "Fm7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Abmaj7", "Abmaj7",
        ],
    },
    {
        "id": 66,
        "title": "Sugar",
        "composer": "Stanley Turrentine",
        "key": "Cm",
        "tempo": 120,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Fm7", "Fm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 67,
        "title": "Tangerine",
        "composer": "Victor Schertzinger",
        "key": "F",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 68,
        "title": "The Girl From Ipanema",
        "composer": "Antonio Carlos Jobim",
        "key": "F",
        "tempo": 140,
        "style": "bossa",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "G7", "G7",
            "Gm7", "F#dim7", "Fmaj7", "D7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "G7", "G7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "G7", "G7",
            "Gm7", "F#dim7", "Fmaj7", "D7",
            "Gm7", "C7", "Am7", "D7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 69,
        "title": "The Shadow Of Your Smile",
        "composer": "Johnny Mandel",
        "key": "Bb",
        "tempo": 80,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Cm7", "F7", "Dm7", "G7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Cm7", "F7", "Dm7", "G7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
        ],
    },
    {
        "id": 70,
        "title": "The Song Is You",
        "composer": "Jerome Kern",
        "key": "C",
        "tempo": 180,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Em7", "Em7", "Am7", "D7",
            "Dm7", "G7", "Em7", "A7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Em7", "Em7", "Am7", "D7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 71,
        "title": "Tune Up",
        "composer": "Miles Davis",
        "key": "D",
        "tempo": 200,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
            "Em7", "A7", "Dmaj7", "Dmaj7",
        ],
    },
    {
        "id": 72,
        "title": "Waltz For Debby",
        "composer": "Bill Evans",
        "key": "F",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Am7", "D7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
            "Gm7", "C7", "Fmaj7", "Fmaj7",
            "Am7", "D7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "Fmaj7", "Fmaj7",
        ],
    },
    {
        "id": 73,
        "title": "Watermelon Man",
        "composer": "Herbie Hancock",
        "key": "F",
        "tempo": 120,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "F7", "F7", "F7", "F7",
            "Bb7", "Bb7", "F7", "F7",
            "Gm7", "C7", "F7", "F7",
            "Gm7", "C7", "F7", "F7",
        ],
    },
    {
        "id": 74,
        "title": "Well You Needn't",
        "composer": "Thelonious Monk",
        "key": "F",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "F6", "F6", "F6", "F6",
            "F6", "F6", "F6", "F6",
            "Db7", "Db7", "F6", "F6",
            "F6", "F6", "F6", "F6",
            "F6", "F6", "F6", "F6",
            "F6", "F6", "F6", "F6",
            "Db7", "Db7", "F6", "F6",
            "F6", "F6", "F6", "F6",
        ],
    },
    {
        "id": 75,
        "title": "Yesterdays",
        "composer": "Jerome Kern",
        "key": "Dm",
        "tempo": 100,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Gm7", "A7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Gm7", "A7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Dm7", "Gm7", "A7", "Dm7",
            "Gm7", "A7", "Dm7", "Dm7",
            "Gm7", "A7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 76,
        "title": "Confirmation",
        "composer": "Charlie Parker",
        "key": "F",
        "tempo": 220,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Fmaj7", "Am7", "Bbmaj7", "G7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Am7", "D7", "Gm7", "Gm7",
            "Cm7", "F7", "Fmaj7", "Fmaj7",
            "Fmaj7", "Am7", "Bbmaj7", "G7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Cm7", "F7", "Bbmaj7", "Bbmaj7",
            "Am7", "D7", "Gm7", "C7",
        ],
    },
    {
        "id": 77,
        "title": "Bags' Groove",
        "composer": "Milt Jackson",
        "key": "F",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "F7", "F7", "F7", "F7",
            "Bb7", "Bb7", "F7", "F7",
            "Gm7", "C7", "F7", "F7",
            "Gm7", "C7", "F7", "F7",
        ],
    },
    {
        "id": 78,
        "title": "Blues For Alice",
        "composer": "Charlie Parker",
        "key": "F",
        "tempo": 160,
        "style": "jazz",
        "form": "blues",
        "bars": 12,
        "progression": [
            "Fmaj7", "Em7", "Eb7", "Dm7",
            "Db7", "Cm7", "F7", "Bbm7",
            "Bbm7", "Am7", "Ab7", "Gm7",
        ],
    },
    {
        "id": 79,
        "title": "Bolivia",
        "composer": "Cedar Walton",
        "key": "Cm",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 24,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 80,
        "title": "Ceora",
        "composer": "Lee Morgan",
        "key": "C",
        "tempo": 110,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
        ],
    },
    {
        "id": 81,
        "title": "Con Alma",
        "composer": "Dizzy Gillespie",
        "key": "D",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Dmaj7", "Dmaj7", "Eb7", "Eb7",
            "Dmaj7", "Dmaj7", "Eb7", "Eb7",
            "Dmaj7", "Dmaj7", "Eb7", "Eb7",
            "Dmaj7", "Dmaj7", "Dmaj7", "Dmaj7",
            "Dmaj7", "Dmaj7", "Eb7", "Eb7",
            "Dmaj7", "Dmaj7", "Eb7", "Eb7",
            "Dmaj7", "Dmaj7", "Eb7", "Eb7",
            "Dmaj7", "Dmaj7", "Dmaj7", "Dmaj7",
        ],
    },
    {
        "id": 82,
        "title": "Darn That Dream",
        "composer": "Jimmy Van Heusen",
        "key": "G",
        "tempo": 80,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
            "Bm7", "E7", "Am7", "D7",
            "Em7", "A7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Am7", "D7",
            "Gmaj7", "Gmaj7", "Gmaj7", "Gmaj7",
        ],
    },
    {
        "id": 83,
        "title": "Day By Day",
        "composer": "Sammy Cahn",
        "key": "C",
        "tempo": 120,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Em7", "Am7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Dm7", "G7",
            "Em7", "Am7", "Dm7", "G7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Am7", "D7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 84,
        "title": "Epistrophy",
        "composer": "Thelonious Monk",
        "key": "Db",
        "tempo": 150,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Db7", "Db7", "Db7", "Db7",
            "Db7", "Db7", "Db7", "Db7",
            "D7", "D7", "D7", "D7",
            "Db7", "Db7", "Db7", "Db7",
        ],
    },
    {
        "id": 85,
        "title": "Four",
        "composer": "Miles Davis",
        "key": "Eb",
        "tempo": 160,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Ebmaj7", "Ebmaj7", "Ebmaj7", "Ebmaj7",
            "Cm7", "F7", "Fm7", "Bb7",
            "Ebmaj7", "Ebmaj7", "Ebmaj7", "Ebmaj7",
            "Cm7", "F7", "Fm7", "Bb7",
            "Dm7", "G7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Ebmaj7", "Ebmaj7", "Cm7", "F7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
        ],
    },
    {
        "id": 86,
        "title": "Half Nelson",
        "composer": "Miles Davis",
        "key": "C",
        "tempo": 200,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cmaj7", "Cmaj7", "Am7", "D7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Cmaj7", "Cmaj7", "Am7", "D7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 87,
        "title": "I Hear A Rhapsody",
        "composer": "George Fragos",
        "key": "Cm",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Fm7", "Bb7", "Ebmaj7", "Ebmaj7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 88,
        "title": "I Love You",
        "composer": "Cole Porter",
        "key": "F",
        "tempo": 140,
        "style": "jazz",
        "form": "AABA",
        "bars": 32,
        "progression": [
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Fmaj7", "Fmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 89,
        "title": "If I Should Lose You",
        "composer": "Robin Rainger",
        "key": "C",
        "tempo": 120,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Cmaj7", "Cmaj7",
            "Am7", "D7", "Dm7", "G7",
            "Em7", "A7", "Dm7", "G7",
            "Cmaj7", "Cmaj7", "Am7", "D7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
            "Dm7", "G7", "Cmaj7", "Cmaj7",
        ],
    },
    {
        "id": 90,
        "title": "Indiana",
        "composer": "James Hanley",
        "key": "C",
        "tempo": 200,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "C6", "C6", "C6", "C6",
            "Dm7", "G7", "C6", "C6",
            "C6", "C6", "C6", "C6",
            "Dm7", "G7", "C6", "C6",
            "Am7", "D7", "Dm7", "G7",
            "C6", "C6", "Dm7", "G7",
            "C6", "C6", "Dm7", "G7",
            "C6", "C6", "C6", "C6",
        ],
    },
    {
        "id": 91,
        "title": "Jordu",
        "composer": "Duke Jordan",
        "key": "Cm",
        "tempo": 160,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 92,
        "title": "La Fiesta",
        "composer": "Chick Corea",
        "key": "Am",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 24,
        "progression": [
            "Am7", "Am7", "Am7", "Am7",
            "Am7", "Am7", "Am7", "Am7",
            "Am7", "Am7", "Am7", "Am7",
            "Am7", "Am7", "Am7", "Am7",
            "Am7", "Am7", "Am7", "Am7",
            "Am7", "Am7", "Am7", "Am7",
        ],
    },
    {
        "id": 93,
        "title": "Lover Man",
        "composer": "Jimmy Davis",
        "key": "Cm",
        "tempo": 80,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "Ab7", "Ab7", "Cm7", "Cm7",
            "G7", "G7", "Cm7", "Cm7",
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "Ab7", "Ab7", "Cm7", "Cm7",
            "G7", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 94,
        "title": "Moanin'",
        "composer": "Bobby Timmons",
        "key": "F",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Fm7", "Fm7", "Fm7", "Fm7",
            "Fm7", "Fm7", "Fm7", "Fm7",
            "Db7", "Db7", "Fm7", "Fm7",
            "Gm7", "C7", "Fm7", "Fm7",
        ],
    },
    {
        "id": 95,
        "title": "Night In Tunisia",
        "composer": "Dizzy Gillespie",
        "key": "Dm",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Ebm7", "Eb7", "Dm7", "Dm7",
            "Am7", "D7", "Gm7", "Gm7",
            "Am7", "D7", "Dm7", "Dm7",
            "Dm7", "Dm7", "Dm7", "Dm7",
            "Ebm7", "Eb7", "Dm7", "Dm7",
            "Am7", "D7", "Gm7", "Gm7",
            "Am7", "D7", "Dm7", "Dm7",
        ],
    },
    {
        "id": 96,
        "title": "Polka Dots And Moonbeams",
        "composer": "Jimmy Van Heusen",
        "key": "Bb",
        "tempo": 80,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Dm7", "G7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Gm7", "C7", "Bbmaj7", "Bbmaj7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Dm7", "G7", "Gm7", "C7",
            "Fmaj7", "Fmaj7", "Dm7", "G7",
            "Gm7", "C7", "Bbmaj7", "Bbmaj7",
        ],
    },
    {
        "id": 97,
        "title": "Sister Sadie",
        "composer": "Horace Silver",
        "key": "Bb",
        "tempo": 150,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Gm7", "C7", "F7", "F7",
            "Bbmaj7", "Bbmaj7", "Bbmaj7", "Bbmaj7",
            "Gm7", "C7", "F7", "Bbmaj7",
        ],
    },
    {
        "id": 98,
        "title": "Tenor Madness",
        "composer": "Sonny Rollins",
        "key": "Bb",
        "tempo": 140,
        "style": "jazz",
        "form": "blues",
        "bars": 12,
        "progression": [
            "Bb7", "Eb7", "Bb7", "Bb7",
            "Eb7", "Eb7", "Bb7", "Bb7",
            "F7", "Eb7", "Bb7", "F7",
        ],
    },
    {
        "id": 99,
        "title": "Unit Seven",
        "composer": "Sam Jones",
        "key": "C",
        "tempo": 130,
        "style": "jazz",
        "form": "AB",
        "bars": 16,
        "progression": [
            "Cm7", "Cm7", "Cm7", "Cm7",
            "Fm7", "Fm7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
            "Dm7b5", "G7", "Cm7", "Cm7",
        ],
    },
    {
        "id": 100,
        "title": "Woody'n You",
        "composer": "Dizzy Gillespie",
        "key": "Ab",
        "tempo": 180,
        "style": "jazz",
        "form": "AB",
        "bars": 32,
        "progression": [
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Abmaj7", "Abmaj7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Bbm7", "Eb7",
            "Abmaj7", "Abmaj7", "Abmaj7", "Abmaj7",
        ],
    },
]
